#!/bin/sh
echo "Making initial commit..."
git init
git add --all
echo "Adding ops subtree."
git commit --author="Cookiecutter (JonathanPorta/cookiecutter-lambda-nodejs-template) - <jonathan@jonathanporta.com>" -m "Initial Commit - Generated by https://github.com/JonathanPorta/cookiecutter-lambda-nodejs-template"
git remote add ops git@github.com:jonathanporta/ops.git --no-tags
git subtree add --prefix ops/ ops master --squash
echo "Project generated."
