---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: {{ cookiecutter.project_slug }}
  description: ""
  annotations:
    github.com/project-slug: {{ cookiecutter.repo_slug }}
spec:
  type: service
  lifecycle: production
